In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('D:\\Data_sets\\creditcard.csv')
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [3]:
df.isnull().sum().sum()

0

In [4]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [5]:
X=df.drop("Class", axis=1)

In [6]:
y=df.Class

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42,stratify=y)

In [8]:
y_train.value_counts()

0    227451
1       394
Name: Class, dtype: int64

In [9]:
y_test.value_counts()

0    56864
1       98
Name: Class, dtype: int64

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, fbeta_score, precision_score, classification_report
from sklearn.model_selection import KFold, GridSearchCV

### LogisticRegression without applying any technique

In [9]:
lg=LogisticRegression()

In [10]:
lg.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [11]:
y_pred=lg.predict(X_test)

In [12]:
print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test, y_pred))

[[56845    27]
 [   28    62]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56872
           1       0.70      0.69      0.69        90

    accuracy                           1.00     56962
   macro avg       0.85      0.84      0.85     56962
weighted avg       1.00      1.00      1.00     56962



### RandomForestClassifier without applying any technique

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
rdf=RandomForestClassifier()

In [30]:
rdf.fit(X_train, y_train)

RandomForestClassifier()

In [31]:
y_pred=rdf.predict(X_test)

In [32]:
confusion_matrix(y_test, y_pred)

array([[56859,     5],
       [   17,    81]], dtype=int64)

In [33]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.94      0.83      0.88        98

    accuracy                           1.00     56962
   macro avg       0.97      0.91      0.94     56962
weighted avg       1.00      1.00      1.00     56962



In [41]:
y_train.value_counts()

0    227464
1       381
Name: Class, dtype: int64

## Using the class_weight parameter

In [13]:
# increasing the class weight of minority class by 100
class_weight=dict({0:1, 1:100})

In [46]:
rdf=RandomForestClassifier(class_weight=class_weight)
rdf.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [47]:
y_pred=rdf.predict(X_test)

In [48]:
confusion_matrix(y_test, y_pred)

array([[56846,     5],
       [   29,    82]], dtype=int64)

In [49]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56851
           1       0.94      0.74      0.83       111

    accuracy                           1.00     56962
   macro avg       0.97      0.87      0.91     56962
weighted avg       1.00      1.00      1.00     56962



## LogisticRegression with StratifiedKFold

In [21]:
from sklearn.model_selection import StratifiedKFold

In [22]:
stf=StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [40]:
lr=LogisticRegression(max_iter=200)

for train_index, test_index  in stf.split(X,y):
    
    X_train_fold, X_test_fold = X.loc[train_index], X.loc[test_index]
    
    y_train_fold, y_test_fold = y.loc[train_index], y.loc[test_index]
    
    print(y_train_fold.value_counts())
    print(y_test_fold.value_counts())

#     lr.fit(X_train_fold, y_train_fold)
    
#     lr.score(X_test_fold, y_test_fold)
    

0    227452
1       393
Name: Class, dtype: int64
0    56863
1       99
Name: Class, dtype: int64
0    227452
1       393
Name: Class, dtype: int64
0    56863
1       99
Name: Class, dtype: int64
0    227452
1       394
Name: Class, dtype: int64
0    56863
1       98
Name: Class, dtype: int64
0    227452
1       394
Name: Class, dtype: int64
0    56863
1       98
Name: Class, dtype: int64
0    227452
1       394
Name: Class, dtype: int64
0    56863
1       98
Name: Class, dtype: int64


In [34]:
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_validate

In [45]:

scoring = {'accuracy' : make_scorer(accuracy_score), 
           'precision' : make_scorer(precision_score),
           'recall' : make_scorer(recall_score), 
           'f1_score' : make_scorer(f1_score)}

stfold =StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
model=LogisticRegression() 


In [46]:
results = cross_validate(estimator=model,X=X, 
                         y=y,
                         cv=stfold,
                        scoring=scoring)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [47]:
results

{'fit_time': array([5.59734321, 5.75379729, 6.01956081, 5.39349437, 5.77160597]),
 'score_time': array([0.10864997, 0.12085295, 0.11495829, 0.11176896, 0.11800623]),
 'test_accuracy': array([0.99892911, 0.99887644, 0.99892909, 0.99875353, 0.9989642 ]),
 'test_precision': array([0.71590909, 0.66990291, 0.69892473, 0.62616822, 0.71910112]),
 'test_recall': array([0.63636364, 0.6969697 , 0.66326531, 0.68367347, 0.65306122]),
 'test_f1_score': array([0.67379679, 0.68316832, 0.68062827, 0.65365854, 0.68449198])}

In [48]:
np.mean(results['test_recall'])

0.6666666666666666

## Under sampling

In [52]:
y_train.value_counts()

0    227464
1       381
Name: Class, dtype: int64

In [50]:
from imblearn.under_sampling import NearMiss

In [14]:
## 0.8 means that take the majority class in such a way that its 80% is equal to minority class

In [53]:
ns=NearMiss(0.8)

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [55]:
X_train_ns, y_train_ns= ns.fit_resample(X_train, y_train)

In [56]:
y_train_ns.value_counts()

0    476
1    381
Name: Class, dtype: int64

In [57]:
476*0.8

380.8

In [58]:
rdf=RandomForestClassifier()
rdf.fit(X_train_ns, y_train_ns)

RandomForestClassifier()

In [59]:
y_pred=rdf.predict(X_test)

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test, y_pred))

[[41538 15313]
 [   10   101]]
              precision    recall  f1-score   support

           0       1.00      0.73      0.84     56851
           1       0.01      0.91      0.01       111

    accuracy                           0.73     56962
   macro avg       0.50      0.82      0.43     56962
weighted avg       1.00      0.73      0.84     56962



## Over sampling

In [60]:
from imblearn.over_sampling import RandomOverSampler

In [61]:
os= RandomOverSampler(0.5)

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [62]:
X_train_os, y_train_os= os.fit_resample(X_train, y_train)

In [67]:
y_train.value_counts()

0    227464
1       381
Name: Class, dtype: int64

In [65]:
y_train_os.value_counts()

0    227464
1    113732
Name: Class, dtype: int64

In [66]:
227464*0.5

113732.0

In [68]:
rdf=RandomForestClassifier()
rdf.fit(X_train_os, y_train_os)

RandomForestClassifier()

In [69]:
y_pred=rdf.predict(X_test)

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test, y_pred))

[[56845     6]
 [   28    83]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56851
           1       0.93      0.75      0.83       111

    accuracy                           1.00     56962
   macro avg       0.97      0.87      0.91     56962
weighted avg       1.00      1.00      1.00     56962



In [70]:
os= RandomOverSampler(0.75)

X_train_os, y_train_os= os.fit_resample(X_train, y_train)

rdf=RandomForestClassifier()

rdf.fit(X_train_os, y_train_os)

y_pred=rdf.predict(X_test)

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test, y_pred))

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


[[56845     6]
 [   27    84]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56851
           1       0.93      0.76      0.84       111

    accuracy                           1.00     56962
   macro avg       0.97      0.88      0.92     56962
weighted avg       1.00      1.00      1.00     56962



## SMOTE

In [73]:
from imblearn.over_sampling import SMOTE

In [78]:
smote=SMOTE(sampling_strategy='minority')

X_train_smote, y_train_smote = smote.fit_resample(X_train,y_train)

In [79]:
y_train.value_counts()

0    227464
1       381
Name: Class, dtype: int64

In [80]:
y_train_smote.value_counts()

0    227464
1    227464
Name: Class, dtype: int64

In [82]:

rdf=RandomForestClassifier()

rdf.fit(X_train_smote, y_train_smote)

y_pred=rdf.predict(X_test)

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test, y_pred))

[[56835    16]
 [   22    89]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56851
           1       0.85      0.80      0.82       111

    accuracy                           1.00     56962
   macro avg       0.92      0.90      0.91     56962
weighted avg       1.00      1.00      1.00     56962



## SMOTETomek

In [22]:
## we can aslo use this library and check out performance

# SMOTETomek is somewhere upsampling and downsampling. SMOTETomek is a hybrid method which is a mixture of the above two 
# methods, it uses an under-sampling method (Tomek) with an oversampling method (SMOTE)

## EasyEnsembleClassifier

In [17]:
# The Easy Ensemble involves creating balanced samples of the training dataset by selecting all examples from 
# the minority class and a subset from the majority class.

In [25]:
from imblearn.ensemble import EasyEnsembleClassifier 

In [28]:
esc=EasyEnsembleClassifier(sampling_strategy='not majority', n_jobs=-1)

In [29]:
esc.fit(X_train,y_train,)

EasyEnsembleClassifier(n_jobs=-1, sampling_strategy='not majority')

In [30]:
y_pred=esc.predict(X_test)

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test, y_pred))

[[56838    26]
 [   27    71]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.73      0.72      0.73        98

    accuracy                           1.00     56962
   macro avg       0.87      0.86      0.86     56962
weighted avg       1.00      1.00      1.00     56962

